/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ttt.h"

void ttt_1(char *host) {
	int player = 0;                              /* Player number - 0 or 1               */
	int go = 0;                                  /* Square selection number for turn     */
	int row = 0;                                 /* Row index for a square               */  
	int column = 0;                              /* Column index for a square            */
	int winner = -1;                              /* The winning player                   */
	int play_res;
	struct play_args args;
	
	CLIENT *clnt;
	char **board;
	int *result;


	if(! (clnt = clnt_create (host, TTT, V1, "udp"))){
		clnt_pcreateerror (host);
		exit (1);
	}

  /* The main game loop. The game continues for up to 9 turns */
  /* As long as there is no winner                            */
	do {
		/* Get valid player square selection */
		do {
			/* Print current board */
			/* replaced currentBoard(buffer); */
			if(! (board = currentboard_1(NULL, clnt))){
				clnt_perror (clnt, "call failed");
				exit(1);
			}
			
			printf("%s\n", *board);
		
        	xdr_free((xdrproc_t)xdr_string, (char*)board);

			printf("\nPlayer %d, please enter the number of the square "
				"where you want to place your %c (or 0 to refresh the board): ", player,(player==1)?'X':'O');
			
			go = -1;
			scanf("%d", &go);
			while (getchar()!='\n'); //clear stdin;

			if (go == -1){ //test user input
				printf("Invalid input. Try again...\n");
				go = 0;
			}
			
			if (go == 0){
				//refresh board	  
				play_res = -1;
				continue;
			}else if (go == 10){
				if(! (result = aocalhas_1(NULL, clnt)) ){
					clnt_perror (clnt, "call failed");
					exit(1);
				}
				play_res = *result;
				continue;
			}

			row = --go/3;                                 /* Get row index of square      */
			column = go%3;                                /* Get column index of square   */
			
			args.row = row;
			args.column = column;
			args.player = player;
			
			if(! (result = play_1(&args, clnt))){
				clnt_perror (clnt, "call failed");
				exit(1);
			}
			play_res = *result;

			if (play_res != 0) {
				switch (play_res) {
					case 1:
						printf("Position outside board.");
						break;
					case 2:
						printf("Square already taken.");
						break;
					case 3:
						printf("Not your turn.");
						break;
					case 4:
						printf("Game has finished.");
						break;
				}
				printf(" Try again...\n");
			}
		} while(play_res != 0);
    
		if(!(result = checkwinner_1(NULL, clnt))){
			clnt_perror (clnt, "call failed");
			exit(1);
		}
		winner = *result;
		
		player = (player+1)%2;
		
		args.player = player;
		if(!play_1(&args, clnt)){		/* Select player */
			clnt_perror (clnt, "call failed");
			exit(1);
		}
		
		//printf("player %d\n", player);

	} while (winner == -1);
  
	/* Game is over so display the final board */
	if(! (board = currentboard_1(NULL, clnt))){
		clnt_perror (clnt, "call failed");
		exit(1);
	}
	printf("%s\n", *board);
        xdr_free((xdrproc_t)xdr_string, (char*)board);
	
	/* Display result message */
	if(winner == 2)
		printf("\nHow boring, it is a draw\n");
	else
		printf("\nCongratulations, player %d, YOU ARE THE WINNER!\n", winner);

	clnt_destroy(clnt);
}


int
main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	ttt_1 (host);
exit (0);
}
